# Generated by Django 3.2.25 on 2025-08-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('ssn', models.CharField(blank=True, max_length=11, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NB', 'Non-binary'), ('O', 'Other'), ('P', 'Prefer not to say')], max_length=10)),
                ('sf_resident', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=10)),
                ('neighborhood', models.CharField(choices=[('mission', 'Mission District'), ('soma', 'South of Market (SoMa)'), ('bayview', 'Bayview-Hunters Point'), ('tenderloin', 'Tenderloin'), ('western', 'Western Addition'), ('other', 'Other San Francisco Area')], default='other', max_length=20)),
                ('demographic_info', models.CharField(choices=[('black', 'Black/African American'), ('white', 'White/Caucasian'), ('latinx', 'Hispanic/Latinx'), ('asian', 'Asian/Pacific Islander'), ('native', 'Native American'), ('mixed', 'Mixed Race'), ('other', 'Other'), ('prefer_not', 'Prefer not to say')], default='other', max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('zh', 'Chinese (Mandarin/Cantonese)'), ('vi', 'Vietnamese'), ('tl', 'Tagalog/Filipino'), ('other', 'Other')], default='en', max_length=10)),
                ('language_other', models.CharField(blank=True, max_length=50, null=True)),
                ('highest_degree', models.CharField(choices=[('none', 'No formal education'), ('elementary', 'Elementary school'), ('middle', 'Middle school'), ('hs', 'High school diploma/GED'), ('some_college', 'Some college'), ('aa', "Associate's degree (AA)"), ('ba', "Bachelor's degree (BA/BS)"), ('ma', "Master's degree (MA/MS)"), ('phd', 'Doctorate (PhD)')], default='none', max_length=20)),
                ('employment_status', models.CharField(choices=[('unemployed', 'Unemployed'), ('part_time', 'Part-time employment'), ('full_time', 'Full-time employment'), ('underemployed', 'Underemployed (seeking better job)'), ('student', 'Student'), ('other', 'Other')], default='unemployed', max_length=20)),
                ('training_interest', models.CharField(choices=[('citybuild', 'CityBuild Academy'), ('citybuild_pro', 'CityBuild Pro | CAPSA'), ('security', 'Security Guard Card Program'), ('construction', 'Construction On Ramp'), ('pit_stop', 'Pit Stop Program'), ('general', 'General job readiness'), ('other', 'Other training')], default='general', max_length=20)),
                ('referral_source', models.CharField(choices=[('friend', 'Friend or family member'), ('social_media', 'Social media'), ('website', 'Website search'), ('job_center', 'Job center/Workforce development'), ('community_org', 'Community organization'), ('walk_in', 'Walk-in visit'), ('other', 'Other')], default='other', max_length=20)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('inactive', 'Inactive')], default='pending', max_length=20)),
                ('staff_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-created_at'],
            },
        ),
    ]
