# Generated by Django 3.2.25 on 2025-05-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('ssn', models.CharField(blank=True, max_length=11)),
                ('homeless', models.BooleanField(default=False)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(default='CA', max_length=2)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('alt_phone', models.CharField(blank=True, max_length=15)),
                ('demographic_info', models.CharField(choices=[('black', 'Black'), ('white', 'White'), ('latinx', 'Latinx'), ('asian', 'Asian'), ('native', 'Native American'), ('other', 'Other')], max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('other', 'Other')], max_length=10)),
                ('language_other', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NB', 'Non-binary'), ('O', 'Other')], max_length=10)),
                ('orientation', models.CharField(choices=[('straight', 'Straight'), ('lgbtq+', 'LGBTQ+'), ('other', 'Other')], max_length=20)),
                ('veteran', models.BooleanField(default=False)),
                ('criminal_justice', models.BooleanField(default=False)),
                ('difficulty_english', models.BooleanField(default=False)),
                ('disabled', models.BooleanField(default=False)),
                ('fostercare', models.BooleanField(default=False)),
                ('single_parent', models.BooleanField(default=False)),
                ('attending_school', models.BooleanField(default=False)),
                ('highest_degree', models.CharField(choices=[('none', 'None'), ('hs', 'High School'), ('aa', 'AA'), ('ba', 'BA'), ('ma', 'MA'), ('phd', 'PhD')], max_length=10)),
                ('employment_status', models.CharField(max_length=100)),
                ('seeking_fulltime', models.BooleanField(default=False)),
                ('recent_hourly_wage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('family_size', models.IntegerField(default=1)),
                ('calfresh', models.BooleanField(default=False)),
                ('calworks', models.BooleanField(default=False)),
                ('caap', models.BooleanField(default=False)),
                ('medi_cal', models.BooleanField(default=False)),
                ('ssdi', models.BooleanField(default=False)),
                ('ssi', models.BooleanField(default=False)),
                ('staff_name', models.CharField(max_length=100)),
                ('nonprofit', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
