# Generated by Django 3.2.25 on 2025-08-15 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='resume',
            field=models.FileField(blank=True, help_text='Upload client resume', null=True, upload_to='resumes/'),
        ),
        migrations.CreateModel(
            name='CaseNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_member', models.CharField(help_text='Staff member who created this note', max_length=100)),
                ('note_type', models.CharField(choices=[('intake', 'Intake Meeting'), ('follow_up', 'Follow-up Call/Visit'), ('training', 'Training Progress'), ('job_search', 'Job Search Support'), ('placement', 'Job Placement'), ('barrier', 'Barrier Assessment'), ('referral', 'Referral to Service'), ('general', 'General Note')], default='general', max_length=20)),
                ('content', models.TextField(help_text='Case note content')),
                ('next_steps', models.TextField(blank=True, help_text='Next steps or action items', null=True)),
                ('follow_up_date', models.DateField(blank=True, help_text='When to follow up', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casenotes', to='clients.client')),
            ],
            options={
                'verbose_name': 'Case Note',
                'verbose_name_plural': 'Case Notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
